import { User, Project, Vulnerability, ActivityEvent, Recommendation, DashboardMetrics } from "./types";

export const mockDb = {
  currentUser: {
    id: "u_1",
    name: "Alex Jensen",
    email: "admin@example.com",
    avatar: "AJ",
    role: "admin",
    workspaceId: "w_1"
  } as User,
  
  metrics: {
    overallScore: 82,
    criticalVulnerabilities: 3,
    highRiskFindings: 12,
    protectedProjects: 4,
    scansThisWeek: 18,
    reportsGenerated: 5
  } as DashboardMetrics,

  projects: [
    { id: "p_1", name: "SubSense", url: "https://subsense.example.com", status: "active", securityScore: 94, lastScanDate: new Date().toISOString(), techStack: ["Next.js", "Tailwind", "PostgreSQL"], openFindings: 2, riskLevel: "Low" },
    { id: "p_2", name: "Festify", url: "https://festify.example.com", status: "active", securityScore: 78, lastScanDate: new Date(Date.now() - 86400000).toISOString(), techStack: ["React", "Express", "MongoDB"], openFindings: 8, riskLevel: "Medium" },
    { id: "p_3", name: "Portfolio Website", url: "https://alexjensen.dev", status: "active", securityScore: 98, lastScanDate: new Date(Date.now() - 86400000 * 2).toISOString(), techStack: ["Astro", "Tailwind"], openFindings: 0, riskLevel: "Low" },
    { id: "p_4", name: "Demo API", url: "https://api.example.com", status: "active", securityScore: 65, lastScanDate: new Date(Date.now() - 86400000 * 5).toISOString(), techStack: ["Django", "PostgreSQL", "Redis"], openFindings: 15, riskLevel: "High" },
  ] as Project[],

  vulnerabilities: [
    { id: "v_1", projectId: "p_4", projectName: "Demo API", title: "SQL Injection in /users endpoint", severity: "Critical", cvss: 9.8, status: "Open", endpoint: "GET /api/v1/users?sort=", discoveredAt: new Date().toISOString() },
    { id: "v_2", projectId: "p_4", projectName: "Demo API", title: "Missing Rate Limiting on Login", severity: "High", cvss: 7.5, status: "Open", endpoint: "POST /api/v1/auth/login", discoveredAt: new Date(Date.now() - 86400000).toISOString() },
    { id: "v_3", projectId: "p_2", projectName: "Festify", title: "Cross-Site Scripting (Reflected)", severity: "High", cvss: 7.2, status: "Open", endpoint: "GET /search?q=", discoveredAt: new Date(Date.now() - 86400000 * 2).toISOString() },
    { id: "v_4", projectId: "p_1", projectName: "SubSense", title: "Outdated React Version", severity: "Medium", cvss: 5.3, status: "Open", endpoint: "Global", discoveredAt: new Date(Date.now() - 86400000 * 3).toISOString() },
  ] as Vulnerability[],

  activities: [
    { id: "a_1", type: "vuln_found", title: "Critical Vulnerability Detected", description: "SQL Injection found in Demo API during scheduled scan.", timestamp: new Date().toISOString(), projectId: "p_4" },
    { id: "a_2", type: "scan_completed", title: "Scan Completed: SubSense", description: "Weekly deep scan completed. Score improved by +4.", timestamp: new Date(Date.now() - 3600000 * 2).toISOString(), projectId: "p_1" },
    { id: "a_3", type: "report_generated", title: "Report Generated", description: "SOC2 Compliance Report for Q3 generated by Alex Jensen.", timestamp: new Date(Date.now() - 3600000 * 24).toISOString() },
    { id: "a_4", type: "project_created", title: "New Project Added", description: "Festify staging environment added to workspace.", timestamp: new Date(Date.now() - 3600000 * 48).toISOString(), projectId: "p_2" },
  ] as ActivityEvent[],

  recommendations: [
    { id: "r_1", title: "Enable Content Security Policy (CSP)", impact: "High", effort: "Medium", description: "Missing CSP headers on Festify and Demo API. Implementing CSP prevents XSS attacks." },
    { id: "r_2", title: "Rotate Postgres Credentials", impact: "High", effort: "Low", description: "Credentials for Demo API haven't been rotated in 180 days." },
    { id: "r_3", title: "Update Express.js", impact: "Medium", effort: "Low", description: "Festify is running Express 4.17. Update to 4.18+ to resolve 2 medium CVEs." },
  ] as Recommendation[],
};

// Simulate network latency
export const delay = (ms: number) => new Promise(res => setTimeout(res, ms));
