"use client";

import { motion } from "framer-motion";
import { FileText, ShieldAlert, CheckCircle2, ChevronDown, Download, Eye } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { useState } from "react";

export function ReportPreview() {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <section className="py-32 relative bg-jet border-y border-white/5">
      <div className="container mx-auto px-6 max-w-5xl">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
            Executive <span className="text-neon">Reporting</span>
          </h2>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Generate compliance-ready reports for SOC2, HIPAA, and PCI-DSS instantly. Preview a sample PDF report generated by our AI engine.
          </p>
        </div>

        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="bg-dark/80 border border-white/10 rounded-2xl p-1 shadow-2xl relative overflow-hidden backdrop-blur-xl"
        >
          {/* Top Bar simulating PDF viewer */}
          <div className="bg-jet border-b border-white/10 p-3 flex justify-between items-center rounded-t-xl">
            <div className="flex items-center gap-2 text-gray-300">
              <FileText className="w-5 h-5" />
              <span className="font-medium text-sm md:text-base">ScureScan_Report_Prod.pdf</span>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" className="hidden sm:flex py-1 px-3 h-auto text-xs">
                <Download className="w-3 h-3 mr-1" /> Download PDF
              </Button>
            </div>
          </div>

          {/* PDF Content Area */}
          <div 
            className={`bg-[#f8f9fa] text-jet p-6 md:p-12 relative overflow-hidden transition-all duration-700 ease-in-out ${isExpanded ? 'max-h-[1500px]' : 'max-h-[450px]'}`}
            style={{ backgroundImage: 'url("https://grainy-gradients.vercel.app/noise.svg")', backgroundBlendMode: 'overlay', opacity: 0.98 }}
          >
            {/* PDF Header */}
            <div className="border-b-2 border-gray-300 pb-6 mb-8 flex flex-col md:flex-row justify-between md:items-end gap-4">
              <div>
                <h1 className="text-3xl md:text-4xl font-bold mb-2 text-gray-900 tracking-tight">Security Assessment Report</h1>
                <p className="text-gray-600 font-medium">Target: prod-api.example.com</p>
                <p className="text-gray-500 text-sm">Date: October 24, 2026</p>
              </div>
              <div className="md:text-right bg-white p-3 rounded border border-gray-200">
                <div className="text-sm font-bold text-gray-800 uppercase tracking-widest mb-1">ScureScan AI</div>
                <div className="text-xs text-red-600 font-bold tracking-wide">Strictly Confidential</div>
              </div>
            </div>

            {/* Executive Summary */}
            <div className="mb-8">
              <h2 className="text-xl font-bold mb-4 text-gray-800 border-b border-gray-200 pb-2">1. Executive Summary</h2>
              <p className="text-gray-700 leading-relaxed text-sm md:text-base">
                This report outlines the findings of the automated security assessment performed on the target infrastructure. The scanning engine identified <strong>3 high-severity</strong> vulnerabilities, 5 medium-severity misconfigurations, and 12 informational notes. Immediate remediation of the high-severity issues is recommended to prevent potential data exfiltration.
              </p>
            </div>

            {/* Risk Breakdown */}
            <div className="grid sm:grid-cols-3 gap-4 mb-8">
              <div className="bg-red-50 border-l-4 border-red-500 p-4 rounded-r shadow-sm">
                <div className="text-red-600 font-bold flex items-center gap-2"><ShieldAlert className="w-4 h-4" /> High Risk</div>
                <div className="text-3xl font-bold text-gray-800 mt-2">3</div>
              </div>
              <div className="bg-yellow-50 border-l-4 border-yellow-500 p-4 rounded-r shadow-sm">
                <div className="text-yellow-600 font-bold flex items-center gap-2"><ShieldAlert className="w-4 h-4" /> Medium Risk</div>
                <div className="text-3xl font-bold text-gray-800 mt-2">5</div>
              </div>
              <div className="bg-green-50 border-l-4 border-green-500 p-4 rounded-r shadow-sm">
                <div className="text-green-600 font-bold flex items-center gap-2"><CheckCircle2 className="w-4 h-4" /> Passed Checks</div>
                <div className="text-3xl font-bold text-gray-800 mt-2">1,042</div>
              </div>
            </div>

            {/* Detailed Findings */}
            <div>
              <h2 className="text-xl font-bold mb-4 text-gray-800 border-b border-gray-200 pb-2">2. Detailed Findings</h2>
              
              <div className="mb-6 pb-6 border-b border-gray-200">
                <div className="flex flex-col md:flex-row md:justify-between md:items-start gap-2 mb-3">
                  <h3 className="text-lg font-bold text-red-600">2.1 SQL Injection in /api/v1/users</h3>
                  <span className="bg-red-100 text-red-700 px-3 py-1 text-xs font-bold rounded shadow-sm self-start">CVSS 9.2 (Critical)</span>
                </div>
                <p className="text-sm text-gray-700 mb-4 leading-relaxed">
                  The 'sort' parameter is directly interpolated into the database query without sanitization. An attacker can append SQL commands to extract user credentials.
                </p>
                <div className="bg-[#1e1e1e] p-4 rounded text-sm font-mono text-green-400 mb-4 shadow-inner overflow-x-auto">
                  GET /api/v1/users?sort=id; DROP TABLE users;--
                </div>
                <h4 className="font-bold text-gray-800 text-sm mb-2 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-green-600"/> Recommended Remediation:</h4>
                <p className="text-sm text-gray-700 bg-green-50 p-3 border-l-2 border-green-500">Implement parameterized queries or use an ORM that automatically sanitizes inputs. Do not concatenate strings to build SQL queries.</p>
              </div>
              
              <div className="mb-6 pb-6 border-b border-gray-200">
                <div className="flex flex-col md:flex-row md:justify-between md:items-start gap-2 mb-3">
                  <h3 className="text-lg font-bold text-yellow-600">2.2 Outdated NGINX Version</h3>
                  <span className="bg-yellow-100 text-yellow-700 px-3 py-1 text-xs font-bold rounded shadow-sm self-start">CVSS 5.3 (Medium)</span>
                </div>
                <p className="text-sm text-gray-700">
                  The server is running NGINX 1.14.0 which contains known vulnerabilities. It is recommended to update to the latest stable release (1.24+).
                </p>
              </div>
            </div>

            {/* Fade Out Gradient when collapsed */}
            {!isExpanded && (
              <div className="absolute bottom-0 left-0 w-full h-48 bg-gradient-to-t from-[#f8f9fa] to-transparent pointer-events-none flex items-end justify-center pb-6">
              </div>
            )}
          </div>
          
          <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-10">
            <Button 
              variant="primary" 
              onClick={() => setIsExpanded(!isExpanded)}
              className="shadow-2xl hover:scale-105 transition-transform"
            >
              {isExpanded ? "Collapse Report" : "Expand Full Report"} <ChevronDown className={`w-4 h-4 ml-1 transition-transform ${isExpanded ? 'rotate-180' : ''}`} />
            </Button>
          </div>

        </motion.div>
      </div>
    </section>
  );
}
